import { Checklist } from '@/types';
import { v4 as uuidv4 } from 'uuid';

export const createDefaultChecklists = (): Checklist[] => [
  {
    id: 'commute',
    name: '通勤',
    emoji: '🚃',
    color: '#4ECDC4',
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: uuidv4(), name: '財布', emoji: '👛', isChecked: false, order: 0, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'スマートフォン', emoji: '📱', isChecked: false, order: 1, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '定期券・ICカード', emoji: '💳', isChecked: false, order: 2, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '鍵', emoji: '🔑', isChecked: false, order: 3, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '社員証', emoji: '🪪', isChecked: false, order: 4, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'ハンカチ', emoji: '🧣', isChecked: false, order: 5, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'ティッシュ', emoji: '🧻', isChecked: false, order: 6, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'イヤホン', emoji: '🎧', isChecked: false, order: 7, forgotCount: 0, checkedCount: 0 },
    ],
  },
  {
    id: 'travel',
    name: '旅行',
    emoji: '✈️',
    color: '#FF6B6B',
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: uuidv4(), name: 'パスポート', emoji: '📕', isChecked: false, order: 0, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '財布', emoji: '👛', isChecked: false, order: 1, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'スマートフォン', emoji: '📱', isChecked: false, order: 2, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '充電器', emoji: '🔌', isChecked: false, order: 3, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '着替え', emoji: '👕', isChecked: false, order: 4, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '洗面用具', emoji: '🪥', isChecked: false, order: 5, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '常備薬', emoji: '💊', isChecked: false, order: 6, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'チケット・予約確認', emoji: '🎫', isChecked: false, order: 7, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'カメラ', emoji: '📷', isChecked: false, order: 8, forgotCount: 0, checkedCount: 0 },
    ],
  },
  {
    id: 'gym',
    name: 'ジム',
    emoji: '💪',
    color: '#45B7D1',
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: uuidv4(), name: 'トレーニングウェア', emoji: '👟', isChecked: false, order: 0, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'シューズ', emoji: '👟', isChecked: false, order: 1, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'タオル', emoji: '🧴', isChecked: false, order: 2, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '水筒', emoji: '🍶', isChecked: false, order: 3, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '会員証', emoji: '💳', isChecked: false, order: 4, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'イヤホン', emoji: '🎧', isChecked: false, order: 5, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'ロッカーキー用小銭', emoji: '🪙', isChecked: false, order: 6, forgotCount: 0, checkedCount: 0 },
    ],
  },
  {
    id: 'date',
    name: 'デート',
    emoji: '💑',
    color: '#F8B500',
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: uuidv4(), name: '財布', emoji: '👛', isChecked: false, order: 0, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'スマートフォン', emoji: '📱', isChecked: false, order: 1, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '鍵', emoji: '🔑', isChecked: false, order: 2, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'ハンカチ', emoji: '🧣', isChecked: false, order: 3, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'ミントタブレット', emoji: '🍬', isChecked: false, order: 4, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'リップクリーム', emoji: '💄', isChecked: false, order: 5, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '予約確認', emoji: '📝', isChecked: false, order: 6, forgotCount: 0, checkedCount: 0 },
    ],
  },
  {
    id: 'outdoor',
    name: 'アウトドア',
    emoji: '🏕️',
    color: '#2ECC71',
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      { id: uuidv4(), name: 'リュック', emoji: '🎒', isChecked: false, order: 0, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '水筒', emoji: '🍶', isChecked: false, order: 1, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '日焼け止め', emoji: '🧴', isChecked: false, order: 2, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '帽子', emoji: '🧢', isChecked: false, order: 3, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'サングラス', emoji: '🕶️', isChecked: false, order: 4, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '虫除けスプレー', emoji: '🦟', isChecked: false, order: 5, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: '救急セット', emoji: '🩹', isChecked: false, order: 6, forgotCount: 0, checkedCount: 0 },
      { id: uuidv4(), name: 'レインウェア', emoji: '🧥', isChecked: false, order: 7, forgotCount: 0, checkedCount: 0 },
    ],
  },
];
